module.exports =function(){
    return {
        
  countries: [ 
  {'country': 'Afghanistan', 'iso': 'AF'}, 
  {'country': 'Åland Islands', 'iso': 'AX'}, 
  {'country': 'Albania', 'iso': 'AL'}, 
  {'country': 'Algeria', 'iso': 'DZ'}, 
  {'country': 'American Samoa', 'iso': 'AS'}, 
  {'country': 'AndorrA', 'iso': 'AD'}, 
  {'country': 'Angola', 'iso': 'AO'}, 
  {'country': 'Anguilla', 'iso': 'AI'}, 
  {'country': 'Antarctica', 'iso': 'AQ'}, 
  {'country': 'Antigua and Barbuda', 'iso': 'AG'}, 
  {'country': 'Argentina', 'iso': 'AR'}, 
  {'country': 'Armenia', 'iso': 'AM'}, 
  {'country': 'Aruba', 'iso': 'AW'}, 
  {'country': 'Australia', 'iso': 'AU'}, 
  {'country': 'Austria', 'iso': 'AT'}, 
  {'country': 'Azerbaijan', 'iso': 'AZ'}, 
  {'country': 'Bahamas', 'iso': 'BS'}, 
  {'country': 'Bahrain', 'iso': 'BH'}, 
  {'country': 'Bangladesh', 'iso': 'BD'}, 
  {'country': 'Barbados', 'iso': 'BB'}, 
  {'country': 'Belarus', 'iso': 'BY'}, 
  {'country': 'Belgium', 'iso': 'BE'}, 
  {'country': 'Belize', 'iso': 'BZ'}, 
  {'country': 'Benin', 'iso': 'BJ'}, 
  {'country': 'Bermuda', 'iso': 'BM'}, 
  {'country': 'Bhutan', 'iso': 'BT'}, 
  {'country': 'Bolivia', 'iso': 'BO'}, 
  {'country': 'Bosnia and Herzegovina', 'iso': 'BA'}, 
  {'country': 'Botswana', 'iso': 'BW'}, 
  {'country': 'Bouvet Island', 'iso': 'BV'}, 
  {'country': 'Brazil', 'iso': 'BR'}, 
  {'country': 'British Indian Ocean Territory', 'iso': 'IO'}, 
  {'country': 'Brunei Darussalam', 'iso': 'BN'}, 
  {'country': 'Bulgaria', 'iso': 'BG'}, 
  {'country': 'Burkina Faso', 'iso': 'BF'}, 
  {'country': 'Burundi', 'iso': 'BI'}, 
  {'country': 'Cambodia', 'iso': 'KH'}, 
  {'country': 'Cameroon', 'iso': 'CM'}, 
  {'country': 'Canada', 'iso': 'CA'}, 
  {'country': 'Cape Verde', 'iso': 'CV'}, 
  {'country': 'Cayman Islands', 'iso': 'KY'}, 
  {'country': 'Central African Republic', 'iso': 'CF'}, 
  {'country': 'Chad', 'iso': 'TD'}, 
  {'country': 'Chile', 'iso': 'CL'}, 
  {'country': 'China', 'iso': 'CN'}, 
  {'country': 'Christmas Island', 'iso': 'CX'}, 
  {'country': 'Cocos (Keeling) Islands', 'iso': 'CC'}, 
  {'country': 'Colombia', 'iso': 'CO'}, 
  {'country': 'Comoros', 'iso': 'KM'}, 
  {'country': 'Congo', 'iso': 'CG'}, 
  {'country': 'Congo, The Democratic Republic of the', 'iso': 'CD'}, 
  {'country': 'Cook Islands', 'iso': 'CK'}, 
  {'country': 'Costa Rica', 'iso': 'CR'}, 
  {'country': 'Cote D\'Ivoire', 'iso': 'CI'}, 
  {'country': 'Croatia', 'iso': 'HR'}, 
  {'country': 'Cuba', 'iso': 'CU'}, 
  {'country': 'Cyprus', 'iso': 'CY'}, 
  {'country': 'Czech Republic', 'iso': 'CZ'}, 
  {'country': 'Denmark', 'iso': 'DK'}, 
  {'country': 'Djibouti', 'iso': 'DJ'}, 
  {'country': 'Dominica', 'iso': 'DM'}, 
  {'country': 'Dominican Republic', 'iso': 'DO'}, 
  {'country': 'Ecuador', 'iso': 'EC'}, 
  {'country': 'Egypt', 'iso': 'EG'}, 
  {'country': 'El Salvador', 'iso': 'SV'}, 
  {'country': 'Equatorial Guinea', 'iso': 'GQ'}, 
  {'country': 'Eritrea', 'iso': 'ER'}, 
  {'country': 'Estonia', 'iso': 'EE'}, 
  {'country': 'Ethiopia', 'iso': 'ET'}, 
  {'country': 'Falkland Islands (Malvinas)', 'iso': 'FK'}, 
  {'country': 'Faroe Islands', 'iso': 'FO'}, 
  {'country': 'Fiji', 'iso': 'FJ'}, 
  {'country': 'Finland', 'iso': 'FI'}, 
  {'country': 'France', 'iso': 'FR'}, 
  {'country': 'French Guiana', 'iso': 'GF'}, 
  {'country': 'French Polynesia', 'iso': 'PF'}, 
  {'country': 'French Southern Territories', 'iso': 'TF'}, 
  {'country': 'Gabon', 'iso': 'GA'}, 
  {'country': 'Gambia', 'iso': 'GM'}, 
  {'country': 'Georgia', 'iso': 'GE'}, 
  {'country': 'Germany', 'iso': 'DE'}, 
  {'country': 'Ghana', 'iso': 'GH'}, 
  {'country': 'Gibraltar', 'iso': 'GI'}, 
  {'country': 'Greece', 'iso': 'GR'}, 
  {'country': 'Greenland', 'iso': 'GL'}, 
  {'country': 'Grenada', 'iso': 'GD'}, 
  {'country': 'Guadeloupe', 'iso': 'GP'}, 
  {'country': 'Guam', 'iso': 'GU'}, 
  {'country': 'Guatemala', 'iso': 'GT'}, 
  {'country': 'Guernsey', 'iso': 'GG'}, 
  {'country': 'Guinea', 'iso': 'GN'}, 
  {'country': 'Guinea-Bissau', 'iso': 'GW'}, 
  {'country': 'Guyana', 'iso': 'GY'}, 
  {'country': 'Haiti', 'iso': 'HT'}, 
  {'country': 'Heard Island and Mcdonald Islands', 'iso': 'HM'}, 
  {'country': 'Holy See (Vatican City State)', 'iso': 'VA'}, 
  {'country': 'Honduras', 'iso': 'HN'}, 
  {'country': 'Hong Kong', 'iso': 'HK'}, 
  {'country': 'Hungary', 'iso': 'HU'}, 
  {'country': 'Iceland', 'iso': 'IS'}, 
  {'country': 'India', 'iso': 'IN'}, 
  {'country': 'Indonesia', 'iso': 'ID'}, 
  {'country': 'Iran, Islamic Republic Of', 'iso': 'IR'}, 
  {'country': 'Iraq', 'iso': 'IQ'}, 
  {'country': 'Ireland', 'iso': 'IE'}, 
  {'country': 'Isle of Man', 'iso': 'IM'}, 
  {'country': 'Israel', 'iso': 'IL'}, 
  {'country': 'Italy', 'iso': 'IT'}, 
  {'country': 'Jamaica', 'iso': 'JM'}, 
  {'country': 'Japan', 'iso': 'JP'}, 
  {'country': 'Jersey', 'iso': 'JE'}, 
  {'country': 'Jordan', 'iso': 'JO'}, 
  {'country': 'Kazakhstan', 'iso': 'KZ'}, 
  {'country': 'Kenya', 'iso': 'KE'}, 
  {'country': 'Kiribati', 'iso': 'KI'}, 
  {'country': 'Korea, Democratic People\'S Republic of', 'iso': 'KP'}, 
  {'country': 'Korea, Republic of', 'iso': 'KR'}, 
  {'country': 'Kuwait', 'iso': 'KW'}, 
  {'country': 'Kyrgyzstan', 'iso': 'KG'}, 
  {'country': 'Lao People\'S Democratic Republic', 'iso': 'LA'}, 
  {'country': 'Latvia', 'iso': 'LV'}, 
  {'country': 'Lebanon', 'iso': 'LB'}, 
  {'country': 'Lesotho', 'iso': 'LS'}, 
  {'country': 'Liberia', 'iso': 'LR'}, 
  {'country': 'Libyan Arab Jamahiriya', 'iso': 'LY'}, 
  {'country': 'Liechtenstein', 'iso': 'LI'}, 
  {'country': 'Lithuania', 'iso': 'LT'}, 
  {'country': 'Luxembourg', 'iso': 'LU'}, 
  {'country': 'Macao', 'iso': 'MO'}, 
  {'country': 'Macedonia, The Former Yugoslav Republic of', 'iso': 'MK'}, 
  {'country': 'Madagascar', 'iso': 'MG'}, 
  {'country': 'Malawi', 'iso': 'MW'}, 
  {'country': 'Malaysia', 'iso': 'MY'}, 
  {'country': 'Maldives', 'iso': 'MV'}, 
  {'country': 'Mali', 'iso': 'ML'}, 
  {'country': 'Malta', 'iso': 'MT'}, 
  {'country': 'Marshall Islands', 'iso': 'MH'}, 
  {'country': 'Martinique', 'iso': 'MQ'}, 
  {'country': 'Mauritania', 'iso': 'MR'}, 
  {'country': 'Mauritius', 'iso': 'MU'}, 
  {'country': 'Mayotte', 'iso': 'YT'}, 
  {'country': 'Mexico', 'iso': 'MX'}, 
  {'country': 'Micronesia, Federated States of', 'iso': 'FM'}, 
  {'country': 'Moldova, Republic of', 'iso': 'MD'}, 
  {'country': 'Monaco', 'iso': 'MC'}, 
  {'country': 'Mongolia', 'iso': 'MN'}, 
  {'country': 'Montserrat', 'iso': 'MS'}, 
  {'country': 'Morocco', 'iso': 'MA'}, 
  {'country': 'Mozambique', 'iso': 'MZ'}, 
  {'country': 'Myanmar', 'iso': 'MM'}, 
  {'country': 'Namibia', 'iso': 'NA'}, 
  {'country': 'Nauru', 'iso': 'NR'}, 
  {'country': 'Nepal', 'iso': 'NP'}, 
  {'country': 'Netherlands', 'iso': 'NL'}, 
  {'country': 'Netherlands Antilles', 'iso': 'AN'}, 
  {'country': 'New Caledonia', 'iso': 'NC'}, 
  {'country': 'New Zealand', 'iso': 'NZ'}, 
  {'country': 'Nicaragua', 'iso': 'NI'}, 
  {'country': 'Niger', 'iso': 'NE'}, 
  {'country': 'Nigeria', 'iso': 'NG'}, 
  {'country': 'Niue', 'iso': 'NU'}, 
  {'country': 'Norfolk Island', 'iso': 'NF'}, 
  {'country': 'Northern Mariana Islands', 'iso': 'MP'}, 
  {'country': 'Norway', 'iso': 'NO'}, 
  {'country': 'Oman', 'iso': 'OM'}, 
  {'country': 'Pakistan', 'iso': 'PK'}, 
  {'country': 'Palau', 'iso': 'PW'}, 
  {'country': 'Palestinian Territory, Occupied', 'iso': 'PS'}, 
  {'country': 'Panama', 'iso': 'PA'}, 
  {'country': 'Papua New Guinea', 'iso': 'PG'}, 
  {'country': 'Paraguay', 'iso': 'PY'}, 
  {'country': 'Peru', 'iso': 'PE'}, 
  {'country': 'Philippines', 'iso': 'PH'}, 
  {'country': 'Pitcairn', 'iso': 'PN'}, 
  {'country': 'Poland', 'iso': 'PL'}, 
  {'country': 'Portugal', 'iso': 'PT'}, 
  {'country': 'Puerto Rico', 'iso': 'PR'}, 
  {'country': 'Qatar', 'iso': 'QA'}, 
  {'country': 'Reunion', 'iso': 'RE'}, 
  {'country': 'Romania', 'iso': 'RO'}, 
  {'country': 'Russian Federation', 'iso': 'RU'}, 
  {'country': 'RWANDA', 'iso': 'RW'}, 
  {'country': 'Saint Helena', 'iso': 'SH'}, 
  {'country': 'Saint Kitts and Nevis', 'iso': 'KN'}, 
  {'country': 'Saint Lucia', 'iso': 'LC'}, 
  {'country': 'Saint Pierre and Miquelon', 'iso': 'PM'}, 
  {'country': 'Saint Vincent and the Grenadines', 'iso': 'VC'}, 
  {'country': 'Samoa', 'iso': 'WS'}, 
  {'country': 'San Marino', 'iso': 'SM'}, 
  {'country': 'Sao Tome and Principe', 'iso': 'ST'}, 
  {'country': 'Saudi Arabia', 'iso': 'SA'}, 
  {'country': 'Senegal', 'iso': 'SN'}, 
  {'country': 'Serbia and Montenegro', 'iso': 'CS'}, 
  {'country': 'Seychelles', 'iso': 'SC'}, 
  {'country': 'Sierra Leone', 'iso': 'SL'}, 
  {'country': 'Singapore', 'iso': 'SG'}, 
  {'country': 'Slovakia', 'iso': 'SK'}, 
  {'country': 'Slovenia', 'iso': 'SI'}, 
  {'country': 'Solomon Islands', 'iso': 'SB'}, 
  {'country': 'Somalia', 'iso': 'SO'}, 
  {'country': 'South Africa', 'iso': 'ZA'}, 
  {'country': 'South Georgia and the South Sandwich Islands', 'iso': 'GS'}, 
  {'country': 'Spain', 'iso': 'ES'}, 
  {'country': 'Sri Lanka', 'iso': 'LK'}, 
  {'country': 'Sudan', 'iso': 'SD'}, 
  {'country': 'Suriname', 'iso': 'SR'}, 
  {'country': 'Svalbard and Jan Mayen', 'iso': 'SJ'}, 
  {'country': 'Swaziland', 'iso': 'SZ'}, 
  {'country': 'Sweden', 'iso': 'SE'}, 
  {'country': 'Switzerland', 'iso': 'CH'}, 
  {'country': 'Syrian Arab Republic', 'iso': 'SY'}, 
  {'country': 'Taiwan, Province of China', 'iso': 'TW'}, 
  {'country': 'Tajikistan', 'iso': 'TJ'}, 
  {'country': 'Tanzania, United Republic of', 'iso': 'TZ'}, 
  {'country': 'Thailand', 'iso': 'TH'}, 
  {'country': 'Timor-Leste', 'iso': 'TL'}, 
  {'country': 'Togo', 'iso': 'TG'}, 
  {'country': 'Tokelau', 'iso': 'TK'}, 
  {'country': 'Tonga', 'iso': 'TO'}, 
  {'country': 'Trinidad and Tobago', 'iso': 'TT'}, 
  {'country': 'Tunisia', 'iso': 'TN'}, 
  {'country': 'Turkey', 'iso': 'TR'}, 
  {'country': 'Turkmenistan', 'iso': 'TM'}, 
  {'country': 'Turks and Caicos Islands', 'iso': 'TC'}, 
  {'country': 'Tuvalu', 'iso': 'TV'}, 
  {'country': 'Uganda', 'iso': 'UG'}, 
  {'country': 'Ukraine', 'iso': 'UA'}, 
  {'country': 'United Arab Emirates', 'iso': 'AE'}, 
  {'country': 'United Kingdom', 'iso': 'GB'}, 
  {'country': 'United States', 'iso': 'US'}, 
  {'country': 'United States Minor Outlying Islands', 'iso': 'UM'}, 
  {'country': 'Uruguay', 'iso': 'UY'}, 
  {'country': 'Uzbekistan', 'iso': 'UZ'}, 
  {'country': 'Vanuatu', 'iso': 'VU'}, 
  {'country': 'Venezuela', 'iso': 'VE'}, 
  {'country': 'Viet Nam', 'iso': 'VN'}, 
  {'country': 'Virgin Islands, British', 'iso': 'VG'}, 
  {'country': 'Virgin Islands, U.S.', 'iso': 'VI'}, 
  {'country': 'Wallis and Futuna', 'iso': 'WF'}, 
  {'country': 'Western Sahara', 'iso': 'EH'}, 
  {'country': 'Yemen', 'iso': 'YE'}, 
  {'country': 'Zambia', 'iso': 'ZM'}, 
  {'country': 'Zimbabwe', 'iso': 'ZW'} 
]
 }
}